import { MutationTree } from 'vuex';

import State from './state';

// Map entity keys generated by normalizr to our state keys.
const entityMapping = {
  categories: 'category',
  comments: 'comment',
  items: 'confession',
  metas: 'facebookInformation',
  tags: 'tag',
};

interface ParamsPayload {
  id: string;
  list: string[];
}

function UPDATE_ENTITIES(state: State, entities: any) {
  Object
    .keys(entityMapping)
    .map((key) => {
      state[key] = Object.assign({}, state[key], entities[entityMapping[key]]);
    });
}

const concat = (type: string) => (state: State, list: string[]) => state[type] = state[type].concat(list);

const UPDATE_FEATURED = concat('featured');
const UPDATE_LATEST = concat('latest');
const UPDATE_POPULAR = concat('popular');

const updateListsByParam = (type: string) => (state: State, payload: ParamsPayload) =>
  state[type][payload.id] = (state[type][payload.id] || []).concat(payload.list);

const UPDATE_LISTS_BY_CATEGORY = updateListsByParam('listsByCategory');
const UPDATE_LISTS_BY_TAG = updateListsByParam('listsByTag');
const UPDATE_LISTS_BY_KEYWORD = updateListsByParam('listsByKeyword');

export default {
  UPDATE_ENTITIES,
  UPDATE_FEATURED,
  UPDATE_LATEST,
  UPDATE_POPULAR,
  UPDATE_LISTS_BY_CATEGORY,
  UPDATE_LISTS_BY_TAG,
  UPDATE_LISTS_BY_KEYWORD,
};
