import { MutationTree } from 'vuex';

import State from './state';

// Map entity keys generated by normalizr to our state keys.
const entityMapping = {
  categories: 'category',
  comments: 'comment',
  items: 'confession',
  metas: 'facebookInformation',
  tags: 'tag',
};

interface ParamsPayload {
  id: string;
  list: string[];
}

const concat = (type: string) => (state: State, list: string[]) => state[type] = state[type].concat(list);

const updateListsByParam = (type: string) => (state: State, payload: ParamsPayload) =>
  state[type][payload.id] = (state[type][payload.id] || []).concat(payload.list);

const updateEntities = (state: State, entities: any) => {
  Object
    .keys(entityMapping)
    .map((key) => {
      state[key] = { ...state[key], ...entities[entityMapping[key]] };
    });
};

export default {
  updateEntities,
  updateFeatured: concat('featured'),
  updateLatest: concat('latest'),
  updateListsByCategory: updateListsByParam('listsByCategory'),
  updateListsByKeyword: updateListsByParam('listsByKeyword'),
  updateListsByTag: updateListsByParam('listsByTag'),
  updatePopular: concat('popular'),
};
